Repository aptly-dev/aptly, pull requests merged in 2018-02, with the labels that each got.

#697 Issues 692
  AUTHORS
  s3/public.go
Labels: 1.3.0

#706 Fix by by-hash index cleanup + root dir data "loss"
  deb/index_files.go
  files/public.go
  files/public_test.go
Labels: 1.3.0, bug

#705 prevent removal of a PublishedStorage's root dir
  files/public.go
  files/public_test.go
Labels: 1.3.0

#703 Add zsh completion function
  AUTHORS
  CONTRIBUTING.md
  Makefile
  completion.d/README-zsh.md
  completion.d/_aptly
  completion.d/aptly
Labels: 1.3.0, enhancement

#707 batch updates to the temporary db when publishing
  deb/publish.go
Labels: 1.3.0
