Repository aptly-dev/aptly, pull requests merged in 2018-04, with the labels that each got.

#713 fix prefix length in error message
  context/context.go
  context/context_test.go
Labels: 1.3.0, bug

#729 Implement 'legacy' Contents indexes to match Ubuntu <=16.04
  Gopkg.lock
  deb/contents.go
  deb/index_files.go
  deb/publish.go
  system/t06_publish/PublishRepo1Test_contents_i386_legacy
  system/t06_publish/repo.py
  system/t06_publish/snapshot.py
  system/t06_publish/switch.py
  system/t06_publish/update.py
Labels: 1.3.0, enhancement

#461 Add systemd service for aptly http server
  aptly-api.service
  aptly.service
Labels: 1.3.0

#730 Replace S3 creds
  .travis.yml
  system/s3_lib.py
  system/swift_lib.py
Labels: 1.3.0

#731 Change build settings to speed up builds
  .gitignore
  .travis.yml
  Makefile
  README.rst
Labels: 1.3.0
