Repository aptly-dev/aptly, pull requests merged in 2024-11, with the labels that each got.

#1386 Fix/add provided package
  .gitattributes
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Makefile
  README.rst
  api/snapshot.go
  cmd/snapshot_pull.go
  deb/import.go
  deb/list.go
  deb/list_test.go
  deb/package_collection.go
  deb/query.go
  system/Dockerfile
  system/files/aptly-fixture.tar.xz
  system/files/etcd.db.xz
  system/t09_repo/AddRepo17Test/mesa-stable-no-march_24.2.6-101pika1_amd64.deb
  system/t09_repo/AddRepo17Test/mesa-stable_24.2.6-101pika1_amd64.deb
  system/t09_repo/AddRepo17Test_gold
  system/t09_repo/AddRepo17Test_repo_show
  system/t09_repo/add.py
Labels: needs review

#1387 package.go: Fix bug in providesDependency
  deb/package.go
  system/t05_snapshot/VerifySnapshot7Test_gold
Labels: needs review

#1390 Make HTTP server wait for tasks before shutdown
  cmd/api_serve.go
  context/context.go
  http/download.go
  http/download_test.go
Labels: bug, needs approval

#1388 do not set empty mirror architectures for flat mirrors
  deb/list.go
  deb/remote.go
  deb/remote_test.go
  system/t04_mirror/CreateMirror14Test_mirror_show
  system/t04_mirror/CreateMirror21Test_mirror_show
  system/t04_mirror/CreateMirror33Test_mirror_show
  system/t04_mirror/CreateMirror34Test_gold
  system/t04_mirror/CreateMirror35Test_gold
  system/t04_mirror/CreateMirror35Test_mirror_show
  system/t04_mirror/ListMirror6Test_gold
  system/t04_mirror/create.py
Labels: needs review, needs approval

#1186 Feature/384-generate-checksums-for-component-files
  AUTHORS
  api/publish.go
  cmd/publish_snapshot.go
  cmd/publish_switch.go
  cmd/publish_update.go
  context/context.go
  deb/index_files.go
  deb/publish.go
  deb/publish_test.go
  man/aptly.1.ronn.tmpl
  system/lib.py
  system/t06_publish/PublishRepo34Test_gold
  system/t06_publish/repo.py
  utils/config_test.go
Labels: needs review, needs approval

#1393 Improve/debianization
  .dockerignore
  .github/workflows/ci.yml
  .gitignore
  Makefile
  debian/aptly-api.maintscript
  debian/aptly-api.postinst
  debian/aptly-api.preinst
  debian/aptly-api.service
  debian/aptly.bash-completion
  debian/aptly.install
  debian/aptly.manpages
  debian/changelog
  debian/compat
  debian/control
  debian/copyright
  debian/manpages
  debian/rules
  debian/tests/control
  debian/upstream/metadata
  debian/watch
  system/Dockerfile
Labels: needs review, needs approval

#1392 Migrate to azure-sdk-for-go
  Makefile
  azure/azure.go
  azure/package_pool.go
  azure/package_pool_test.go
  azure/public.go
  azure/public_test.go
  context/context.go
  deb/list.go
  go.mod
  go.sum
  system/Dockerfile
Labels: needs review, help wanted !
